---
- name: Recompile Enhydris {{ enhydris_instance_name }}
  command: /usr/bin/python3 -OO -m compileall -x '^/opt/enhydris-{{ enhydris_instance_name }}/venv/' /opt/enhydris-{{ enhydris_instance_name }} /etc/opt/enhydris/{{ enhydris_instance_name }}
  notify:
    - Restart Enhydris {{ enhydris_instance_name }}

- name: "Collect Enhydris {{ enhydris_instance_name }} static files"
  shell: >
    export PYTHONPATH=/etc/opt/enhydris/{{ enhydris_instance_name }} &&
    export DJANGO_SETTINGS_MODULE=settings &&
    ./venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: "/opt/enhydris-{{ enhydris_instance_name }}"

- name: "Restart Enhydris {{ enhydris_instance_name }}"
  # We don't use the systemd module because it doesn't support globs
  shell: >
    systemctl daemon-reload &&
    service enhydris-{{ enhydris_instance_name }}-* restart
